# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/catlord/Documents/zimny_semester_2019-20/grafika/cvika/ppgso

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/catlord/Documents/zimny_semester_2019-20/grafika/cvika/ppgso

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/catlord/Documents/zimny_semester_2019-20/grafika/cvika/ppgso/CMakeFiles /home/catlord/Documents/zimny_semester_2019-20/grafika/cvika/ppgso/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/catlord/Documents/zimny_semester_2019-20/grafika/cvika/ppgso/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named testing

# Build rule for target.
testing: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 testing
.PHONY : testing

# fast build rule for target.
testing/fast:
	$(MAKE) -f CMakeFiles/testing.dir/build.make CMakeFiles/testing.dir/build
.PHONY : testing/fast

#=============================================================================
# Target rules for targets named playground

# Build rule for target.
playground: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 playground
.PHONY : playground

# fast build rule for target.
playground/fast:
	$(MAKE) -f CMakeFiles/playground.dir/build.make CMakeFiles/playground.dir/build
.PHONY : playground/fast

#=============================================================================
# Target rules for targets named ppgso

# Build rule for target.
ppgso: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ppgso
.PHONY : ppgso

# fast build rule for target.
ppgso/fast:
	$(MAKE) -f CMakeFiles/ppgso.dir/build.make CMakeFiles/ppgso.dir/build
.PHONY : ppgso/fast

#=============================================================================
# Target rules for targets named shaders

# Build rule for target.
shaders: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 shaders
.PHONY : shaders

# fast build rule for target.
shaders/fast:
	$(MAKE) -f CMakeFiles/shaders.dir/build.make CMakeFiles/shaders.dir/build
.PHONY : shaders/fast

ppgso/image.o: ppgso/image.cpp.o

.PHONY : ppgso/image.o

# target to build an object file
ppgso/image.cpp.o:
	$(MAKE) -f CMakeFiles/ppgso.dir/build.make CMakeFiles/ppgso.dir/ppgso/image.cpp.o
.PHONY : ppgso/image.cpp.o

ppgso/image.i: ppgso/image.cpp.i

.PHONY : ppgso/image.i

# target to preprocess a source file
ppgso/image.cpp.i:
	$(MAKE) -f CMakeFiles/ppgso.dir/build.make CMakeFiles/ppgso.dir/ppgso/image.cpp.i
.PHONY : ppgso/image.cpp.i

ppgso/image.s: ppgso/image.cpp.s

.PHONY : ppgso/image.s

# target to generate assembly for a file
ppgso/image.cpp.s:
	$(MAKE) -f CMakeFiles/ppgso.dir/build.make CMakeFiles/ppgso.dir/ppgso/image.cpp.s
.PHONY : ppgso/image.cpp.s

ppgso/image_bmp.o: ppgso/image_bmp.cpp.o

.PHONY : ppgso/image_bmp.o

# target to build an object file
ppgso/image_bmp.cpp.o:
	$(MAKE) -f CMakeFiles/ppgso.dir/build.make CMakeFiles/ppgso.dir/ppgso/image_bmp.cpp.o
.PHONY : ppgso/image_bmp.cpp.o

ppgso/image_bmp.i: ppgso/image_bmp.cpp.i

.PHONY : ppgso/image_bmp.i

# target to preprocess a source file
ppgso/image_bmp.cpp.i:
	$(MAKE) -f CMakeFiles/ppgso.dir/build.make CMakeFiles/ppgso.dir/ppgso/image_bmp.cpp.i
.PHONY : ppgso/image_bmp.cpp.i

ppgso/image_bmp.s: ppgso/image_bmp.cpp.s

.PHONY : ppgso/image_bmp.s

# target to generate assembly for a file
ppgso/image_bmp.cpp.s:
	$(MAKE) -f CMakeFiles/ppgso.dir/build.make CMakeFiles/ppgso.dir/ppgso/image_bmp.cpp.s
.PHONY : ppgso/image_bmp.cpp.s

ppgso/image_raw.o: ppgso/image_raw.cpp.o

.PHONY : ppgso/image_raw.o

# target to build an object file
ppgso/image_raw.cpp.o:
	$(MAKE) -f CMakeFiles/ppgso.dir/build.make CMakeFiles/ppgso.dir/ppgso/image_raw.cpp.o
.PHONY : ppgso/image_raw.cpp.o

ppgso/image_raw.i: ppgso/image_raw.cpp.i

.PHONY : ppgso/image_raw.i

# target to preprocess a source file
ppgso/image_raw.cpp.i:
	$(MAKE) -f CMakeFiles/ppgso.dir/build.make CMakeFiles/ppgso.dir/ppgso/image_raw.cpp.i
.PHONY : ppgso/image_raw.cpp.i

ppgso/image_raw.s: ppgso/image_raw.cpp.s

.PHONY : ppgso/image_raw.s

# target to generate assembly for a file
ppgso/image_raw.cpp.s:
	$(MAKE) -f CMakeFiles/ppgso.dir/build.make CMakeFiles/ppgso.dir/ppgso/image_raw.cpp.s
.PHONY : ppgso/image_raw.cpp.s

ppgso/mesh.o: ppgso/mesh.cpp.o

.PHONY : ppgso/mesh.o

# target to build an object file
ppgso/mesh.cpp.o:
	$(MAKE) -f CMakeFiles/ppgso.dir/build.make CMakeFiles/ppgso.dir/ppgso/mesh.cpp.o
.PHONY : ppgso/mesh.cpp.o

ppgso/mesh.i: ppgso/mesh.cpp.i

.PHONY : ppgso/mesh.i

# target to preprocess a source file
ppgso/mesh.cpp.i:
	$(MAKE) -f CMakeFiles/ppgso.dir/build.make CMakeFiles/ppgso.dir/ppgso/mesh.cpp.i
.PHONY : ppgso/mesh.cpp.i

ppgso/mesh.s: ppgso/mesh.cpp.s

.PHONY : ppgso/mesh.s

# target to generate assembly for a file
ppgso/mesh.cpp.s:
	$(MAKE) -f CMakeFiles/ppgso.dir/build.make CMakeFiles/ppgso.dir/ppgso/mesh.cpp.s
.PHONY : ppgso/mesh.cpp.s

ppgso/shader.o: ppgso/shader.cpp.o

.PHONY : ppgso/shader.o

# target to build an object file
ppgso/shader.cpp.o:
	$(MAKE) -f CMakeFiles/ppgso.dir/build.make CMakeFiles/ppgso.dir/ppgso/shader.cpp.o
.PHONY : ppgso/shader.cpp.o

ppgso/shader.i: ppgso/shader.cpp.i

.PHONY : ppgso/shader.i

# target to preprocess a source file
ppgso/shader.cpp.i:
	$(MAKE) -f CMakeFiles/ppgso.dir/build.make CMakeFiles/ppgso.dir/ppgso/shader.cpp.i
.PHONY : ppgso/shader.cpp.i

ppgso/shader.s: ppgso/shader.cpp.s

.PHONY : ppgso/shader.s

# target to generate assembly for a file
ppgso/shader.cpp.s:
	$(MAKE) -f CMakeFiles/ppgso.dir/build.make CMakeFiles/ppgso.dir/ppgso/shader.cpp.s
.PHONY : ppgso/shader.cpp.s

ppgso/texture.o: ppgso/texture.cpp.o

.PHONY : ppgso/texture.o

# target to build an object file
ppgso/texture.cpp.o:
	$(MAKE) -f CMakeFiles/ppgso.dir/build.make CMakeFiles/ppgso.dir/ppgso/texture.cpp.o
.PHONY : ppgso/texture.cpp.o

ppgso/texture.i: ppgso/texture.cpp.i

.PHONY : ppgso/texture.i

# target to preprocess a source file
ppgso/texture.cpp.i:
	$(MAKE) -f CMakeFiles/ppgso.dir/build.make CMakeFiles/ppgso.dir/ppgso/texture.cpp.i
.PHONY : ppgso/texture.cpp.i

ppgso/texture.s: ppgso/texture.cpp.s

.PHONY : ppgso/texture.s

# target to generate assembly for a file
ppgso/texture.cpp.s:
	$(MAKE) -f CMakeFiles/ppgso.dir/build.make CMakeFiles/ppgso.dir/ppgso/texture.cpp.s
.PHONY : ppgso/texture.cpp.s

ppgso/tiny_obj_loader.o: ppgso/tiny_obj_loader.cpp.o

.PHONY : ppgso/tiny_obj_loader.o

# target to build an object file
ppgso/tiny_obj_loader.cpp.o:
	$(MAKE) -f CMakeFiles/ppgso.dir/build.make CMakeFiles/ppgso.dir/ppgso/tiny_obj_loader.cpp.o
.PHONY : ppgso/tiny_obj_loader.cpp.o

ppgso/tiny_obj_loader.i: ppgso/tiny_obj_loader.cpp.i

.PHONY : ppgso/tiny_obj_loader.i

# target to preprocess a source file
ppgso/tiny_obj_loader.cpp.i:
	$(MAKE) -f CMakeFiles/ppgso.dir/build.make CMakeFiles/ppgso.dir/ppgso/tiny_obj_loader.cpp.i
.PHONY : ppgso/tiny_obj_loader.cpp.i

ppgso/tiny_obj_loader.s: ppgso/tiny_obj_loader.cpp.s

.PHONY : ppgso/tiny_obj_loader.s

# target to generate assembly for a file
ppgso/tiny_obj_loader.cpp.s:
	$(MAKE) -f CMakeFiles/ppgso.dir/build.make CMakeFiles/ppgso.dir/ppgso/tiny_obj_loader.cpp.s
.PHONY : ppgso/tiny_obj_loader.cpp.s

ppgso/window.o: ppgso/window.cpp.o

.PHONY : ppgso/window.o

# target to build an object file
ppgso/window.cpp.o:
	$(MAKE) -f CMakeFiles/ppgso.dir/build.make CMakeFiles/ppgso.dir/ppgso/window.cpp.o
.PHONY : ppgso/window.cpp.o

ppgso/window.i: ppgso/window.cpp.i

.PHONY : ppgso/window.i

# target to preprocess a source file
ppgso/window.cpp.i:
	$(MAKE) -f CMakeFiles/ppgso.dir/build.make CMakeFiles/ppgso.dir/ppgso/window.cpp.i
.PHONY : ppgso/window.cpp.i

ppgso/window.s: ppgso/window.cpp.s

.PHONY : ppgso/window.s

# target to generate assembly for a file
ppgso/window.cpp.s:
	$(MAKE) -f CMakeFiles/ppgso.dir/build.make CMakeFiles/ppgso.dir/ppgso/window.cpp.s
.PHONY : ppgso/window.cpp.s

shaders/color_frag_glsl.o: shaders/color_frag_glsl.cpp.o

.PHONY : shaders/color_frag_glsl.o

# target to build an object file
shaders/color_frag_glsl.cpp.o:
	$(MAKE) -f CMakeFiles/shaders.dir/build.make CMakeFiles/shaders.dir/shaders/color_frag_glsl.cpp.o
.PHONY : shaders/color_frag_glsl.cpp.o

shaders/color_frag_glsl.i: shaders/color_frag_glsl.cpp.i

.PHONY : shaders/color_frag_glsl.i

# target to preprocess a source file
shaders/color_frag_glsl.cpp.i:
	$(MAKE) -f CMakeFiles/shaders.dir/build.make CMakeFiles/shaders.dir/shaders/color_frag_glsl.cpp.i
.PHONY : shaders/color_frag_glsl.cpp.i

shaders/color_frag_glsl.s: shaders/color_frag_glsl.cpp.s

.PHONY : shaders/color_frag_glsl.s

# target to generate assembly for a file
shaders/color_frag_glsl.cpp.s:
	$(MAKE) -f CMakeFiles/shaders.dir/build.make CMakeFiles/shaders.dir/shaders/color_frag_glsl.cpp.s
.PHONY : shaders/color_frag_glsl.cpp.s

shaders/color_vert_glsl.o: shaders/color_vert_glsl.cpp.o

.PHONY : shaders/color_vert_glsl.o

# target to build an object file
shaders/color_vert_glsl.cpp.o:
	$(MAKE) -f CMakeFiles/shaders.dir/build.make CMakeFiles/shaders.dir/shaders/color_vert_glsl.cpp.o
.PHONY : shaders/color_vert_glsl.cpp.o

shaders/color_vert_glsl.i: shaders/color_vert_glsl.cpp.i

.PHONY : shaders/color_vert_glsl.i

# target to preprocess a source file
shaders/color_vert_glsl.cpp.i:
	$(MAKE) -f CMakeFiles/shaders.dir/build.make CMakeFiles/shaders.dir/shaders/color_vert_glsl.cpp.i
.PHONY : shaders/color_vert_glsl.cpp.i

shaders/color_vert_glsl.s: shaders/color_vert_glsl.cpp.s

.PHONY : shaders/color_vert_glsl.s

# target to generate assembly for a file
shaders/color_vert_glsl.cpp.s:
	$(MAKE) -f CMakeFiles/shaders.dir/build.make CMakeFiles/shaders.dir/shaders/color_vert_glsl.cpp.s
.PHONY : shaders/color_vert_glsl.cpp.s

shaders/convolution_frag_glsl.o: shaders/convolution_frag_glsl.cpp.o

.PHONY : shaders/convolution_frag_glsl.o

# target to build an object file
shaders/convolution_frag_glsl.cpp.o:
	$(MAKE) -f CMakeFiles/shaders.dir/build.make CMakeFiles/shaders.dir/shaders/convolution_frag_glsl.cpp.o
.PHONY : shaders/convolution_frag_glsl.cpp.o

shaders/convolution_frag_glsl.i: shaders/convolution_frag_glsl.cpp.i

.PHONY : shaders/convolution_frag_glsl.i

# target to preprocess a source file
shaders/convolution_frag_glsl.cpp.i:
	$(MAKE) -f CMakeFiles/shaders.dir/build.make CMakeFiles/shaders.dir/shaders/convolution_frag_glsl.cpp.i
.PHONY : shaders/convolution_frag_glsl.cpp.i

shaders/convolution_frag_glsl.s: shaders/convolution_frag_glsl.cpp.s

.PHONY : shaders/convolution_frag_glsl.s

# target to generate assembly for a file
shaders/convolution_frag_glsl.cpp.s:
	$(MAKE) -f CMakeFiles/shaders.dir/build.make CMakeFiles/shaders.dir/shaders/convolution_frag_glsl.cpp.s
.PHONY : shaders/convolution_frag_glsl.cpp.s

shaders/convolution_vert_glsl.o: shaders/convolution_vert_glsl.cpp.o

.PHONY : shaders/convolution_vert_glsl.o

# target to build an object file
shaders/convolution_vert_glsl.cpp.o:
	$(MAKE) -f CMakeFiles/shaders.dir/build.make CMakeFiles/shaders.dir/shaders/convolution_vert_glsl.cpp.o
.PHONY : shaders/convolution_vert_glsl.cpp.o

shaders/convolution_vert_glsl.i: shaders/convolution_vert_glsl.cpp.i

.PHONY : shaders/convolution_vert_glsl.i

# target to preprocess a source file
shaders/convolution_vert_glsl.cpp.i:
	$(MAKE) -f CMakeFiles/shaders.dir/build.make CMakeFiles/shaders.dir/shaders/convolution_vert_glsl.cpp.i
.PHONY : shaders/convolution_vert_glsl.cpp.i

shaders/convolution_vert_glsl.s: shaders/convolution_vert_glsl.cpp.s

.PHONY : shaders/convolution_vert_glsl.s

# target to generate assembly for a file
shaders/convolution_vert_glsl.cpp.s:
	$(MAKE) -f CMakeFiles/shaders.dir/build.make CMakeFiles/shaders.dir/shaders/convolution_vert_glsl.cpp.s
.PHONY : shaders/convolution_vert_glsl.cpp.s

shaders/diffuse_frag_glsl.o: shaders/diffuse_frag_glsl.cpp.o

.PHONY : shaders/diffuse_frag_glsl.o

# target to build an object file
shaders/diffuse_frag_glsl.cpp.o:
	$(MAKE) -f CMakeFiles/shaders.dir/build.make CMakeFiles/shaders.dir/shaders/diffuse_frag_glsl.cpp.o
.PHONY : shaders/diffuse_frag_glsl.cpp.o

shaders/diffuse_frag_glsl.i: shaders/diffuse_frag_glsl.cpp.i

.PHONY : shaders/diffuse_frag_glsl.i

# target to preprocess a source file
shaders/diffuse_frag_glsl.cpp.i:
	$(MAKE) -f CMakeFiles/shaders.dir/build.make CMakeFiles/shaders.dir/shaders/diffuse_frag_glsl.cpp.i
.PHONY : shaders/diffuse_frag_glsl.cpp.i

shaders/diffuse_frag_glsl.s: shaders/diffuse_frag_glsl.cpp.s

.PHONY : shaders/diffuse_frag_glsl.s

# target to generate assembly for a file
shaders/diffuse_frag_glsl.cpp.s:
	$(MAKE) -f CMakeFiles/shaders.dir/build.make CMakeFiles/shaders.dir/shaders/diffuse_frag_glsl.cpp.s
.PHONY : shaders/diffuse_frag_glsl.cpp.s

shaders/diffuse_vert_glsl.o: shaders/diffuse_vert_glsl.cpp.o

.PHONY : shaders/diffuse_vert_glsl.o

# target to build an object file
shaders/diffuse_vert_glsl.cpp.o:
	$(MAKE) -f CMakeFiles/shaders.dir/build.make CMakeFiles/shaders.dir/shaders/diffuse_vert_glsl.cpp.o
.PHONY : shaders/diffuse_vert_glsl.cpp.o

shaders/diffuse_vert_glsl.i: shaders/diffuse_vert_glsl.cpp.i

.PHONY : shaders/diffuse_vert_glsl.i

# target to preprocess a source file
shaders/diffuse_vert_glsl.cpp.i:
	$(MAKE) -f CMakeFiles/shaders.dir/build.make CMakeFiles/shaders.dir/shaders/diffuse_vert_glsl.cpp.i
.PHONY : shaders/diffuse_vert_glsl.cpp.i

shaders/diffuse_vert_glsl.s: shaders/diffuse_vert_glsl.cpp.s

.PHONY : shaders/diffuse_vert_glsl.s

# target to generate assembly for a file
shaders/diffuse_vert_glsl.cpp.s:
	$(MAKE) -f CMakeFiles/shaders.dir/build.make CMakeFiles/shaders.dir/shaders/diffuse_vert_glsl.cpp.s
.PHONY : shaders/diffuse_vert_glsl.cpp.s

shaders/texture_frag_glsl.o: shaders/texture_frag_glsl.cpp.o

.PHONY : shaders/texture_frag_glsl.o

# target to build an object file
shaders/texture_frag_glsl.cpp.o:
	$(MAKE) -f CMakeFiles/shaders.dir/build.make CMakeFiles/shaders.dir/shaders/texture_frag_glsl.cpp.o
.PHONY : shaders/texture_frag_glsl.cpp.o

shaders/texture_frag_glsl.i: shaders/texture_frag_glsl.cpp.i

.PHONY : shaders/texture_frag_glsl.i

# target to preprocess a source file
shaders/texture_frag_glsl.cpp.i:
	$(MAKE) -f CMakeFiles/shaders.dir/build.make CMakeFiles/shaders.dir/shaders/texture_frag_glsl.cpp.i
.PHONY : shaders/texture_frag_glsl.cpp.i

shaders/texture_frag_glsl.s: shaders/texture_frag_glsl.cpp.s

.PHONY : shaders/texture_frag_glsl.s

# target to generate assembly for a file
shaders/texture_frag_glsl.cpp.s:
	$(MAKE) -f CMakeFiles/shaders.dir/build.make CMakeFiles/shaders.dir/shaders/texture_frag_glsl.cpp.s
.PHONY : shaders/texture_frag_glsl.cpp.s

shaders/texture_vert_glsl.o: shaders/texture_vert_glsl.cpp.o

.PHONY : shaders/texture_vert_glsl.o

# target to build an object file
shaders/texture_vert_glsl.cpp.o:
	$(MAKE) -f CMakeFiles/shaders.dir/build.make CMakeFiles/shaders.dir/shaders/texture_vert_glsl.cpp.o
.PHONY : shaders/texture_vert_glsl.cpp.o

shaders/texture_vert_glsl.i: shaders/texture_vert_glsl.cpp.i

.PHONY : shaders/texture_vert_glsl.i

# target to preprocess a source file
shaders/texture_vert_glsl.cpp.i:
	$(MAKE) -f CMakeFiles/shaders.dir/build.make CMakeFiles/shaders.dir/shaders/texture_vert_glsl.cpp.i
.PHONY : shaders/texture_vert_glsl.cpp.i

shaders/texture_vert_glsl.s: shaders/texture_vert_glsl.cpp.s

.PHONY : shaders/texture_vert_glsl.s

# target to generate assembly for a file
shaders/texture_vert_glsl.cpp.s:
	$(MAKE) -f CMakeFiles/shaders.dir/build.make CMakeFiles/shaders.dir/shaders/texture_vert_glsl.cpp.s
.PHONY : shaders/texture_vert_glsl.cpp.s

src/playground/camera.o: src/playground/camera.cpp.o

.PHONY : src/playground/camera.o

# target to build an object file
src/playground/camera.cpp.o:
	$(MAKE) -f CMakeFiles/playground.dir/build.make CMakeFiles/playground.dir/src/playground/camera.cpp.o
.PHONY : src/playground/camera.cpp.o

src/playground/camera.i: src/playground/camera.cpp.i

.PHONY : src/playground/camera.i

# target to preprocess a source file
src/playground/camera.cpp.i:
	$(MAKE) -f CMakeFiles/playground.dir/build.make CMakeFiles/playground.dir/src/playground/camera.cpp.i
.PHONY : src/playground/camera.cpp.i

src/playground/camera.s: src/playground/camera.cpp.s

.PHONY : src/playground/camera.s

# target to generate assembly for a file
src/playground/camera.cpp.s:
	$(MAKE) -f CMakeFiles/playground.dir/build.make CMakeFiles/playground.dir/src/playground/camera.cpp.s
.PHONY : src/playground/camera.cpp.s

src/playground/cube.o: src/playground/cube.cpp.o

.PHONY : src/playground/cube.o

# target to build an object file
src/playground/cube.cpp.o:
	$(MAKE) -f CMakeFiles/playground.dir/build.make CMakeFiles/playground.dir/src/playground/cube.cpp.o
.PHONY : src/playground/cube.cpp.o

src/playground/cube.i: src/playground/cube.cpp.i

.PHONY : src/playground/cube.i

# target to preprocess a source file
src/playground/cube.cpp.i:
	$(MAKE) -f CMakeFiles/playground.dir/build.make CMakeFiles/playground.dir/src/playground/cube.cpp.i
.PHONY : src/playground/cube.cpp.i

src/playground/cube.s: src/playground/cube.cpp.s

.PHONY : src/playground/cube.s

# target to generate assembly for a file
src/playground/cube.cpp.s:
	$(MAKE) -f CMakeFiles/playground.dir/build.make CMakeFiles/playground.dir/src/playground/cube.cpp.s
.PHONY : src/playground/cube.cpp.s

src/playground/explosion.o: src/playground/explosion.cpp.o

.PHONY : src/playground/explosion.o

# target to build an object file
src/playground/explosion.cpp.o:
	$(MAKE) -f CMakeFiles/playground.dir/build.make CMakeFiles/playground.dir/src/playground/explosion.cpp.o
.PHONY : src/playground/explosion.cpp.o

src/playground/explosion.i: src/playground/explosion.cpp.i

.PHONY : src/playground/explosion.i

# target to preprocess a source file
src/playground/explosion.cpp.i:
	$(MAKE) -f CMakeFiles/playground.dir/build.make CMakeFiles/playground.dir/src/playground/explosion.cpp.i
.PHONY : src/playground/explosion.cpp.i

src/playground/explosion.s: src/playground/explosion.cpp.s

.PHONY : src/playground/explosion.s

# target to generate assembly for a file
src/playground/explosion.cpp.s:
	$(MAKE) -f CMakeFiles/playground.dir/build.make CMakeFiles/playground.dir/src/playground/explosion.cpp.s
.PHONY : src/playground/explosion.cpp.s

src/playground/lamppost.o: src/playground/lamppost.cpp.o

.PHONY : src/playground/lamppost.o

# target to build an object file
src/playground/lamppost.cpp.o:
	$(MAKE) -f CMakeFiles/playground.dir/build.make CMakeFiles/playground.dir/src/playground/lamppost.cpp.o
.PHONY : src/playground/lamppost.cpp.o

src/playground/lamppost.i: src/playground/lamppost.cpp.i

.PHONY : src/playground/lamppost.i

# target to preprocess a source file
src/playground/lamppost.cpp.i:
	$(MAKE) -f CMakeFiles/playground.dir/build.make CMakeFiles/playground.dir/src/playground/lamppost.cpp.i
.PHONY : src/playground/lamppost.cpp.i

src/playground/lamppost.s: src/playground/lamppost.cpp.s

.PHONY : src/playground/lamppost.s

# target to generate assembly for a file
src/playground/lamppost.cpp.s:
	$(MAKE) -f CMakeFiles/playground.dir/build.make CMakeFiles/playground.dir/src/playground/lamppost.cpp.s
.PHONY : src/playground/lamppost.cpp.s

src/playground/main.o: src/playground/main.cpp.o

.PHONY : src/playground/main.o

# target to build an object file
src/playground/main.cpp.o:
	$(MAKE) -f CMakeFiles/playground.dir/build.make CMakeFiles/playground.dir/src/playground/main.cpp.o
.PHONY : src/playground/main.cpp.o

src/playground/main.i: src/playground/main.cpp.i

.PHONY : src/playground/main.i

# target to preprocess a source file
src/playground/main.cpp.i:
	$(MAKE) -f CMakeFiles/playground.dir/build.make CMakeFiles/playground.dir/src/playground/main.cpp.i
.PHONY : src/playground/main.cpp.i

src/playground/main.s: src/playground/main.cpp.s

.PHONY : src/playground/main.s

# target to generate assembly for a file
src/playground/main.cpp.s:
	$(MAKE) -f CMakeFiles/playground.dir/build.make CMakeFiles/playground.dir/src/playground/main.cpp.s
.PHONY : src/playground/main.cpp.s

src/playground/menu.o: src/playground/menu.cpp.o

.PHONY : src/playground/menu.o

# target to build an object file
src/playground/menu.cpp.o:
	$(MAKE) -f CMakeFiles/playground.dir/build.make CMakeFiles/playground.dir/src/playground/menu.cpp.o
.PHONY : src/playground/menu.cpp.o

src/playground/menu.i: src/playground/menu.cpp.i

.PHONY : src/playground/menu.i

# target to preprocess a source file
src/playground/menu.cpp.i:
	$(MAKE) -f CMakeFiles/playground.dir/build.make CMakeFiles/playground.dir/src/playground/menu.cpp.i
.PHONY : src/playground/menu.cpp.i

src/playground/menu.s: src/playground/menu.cpp.s

.PHONY : src/playground/menu.s

# target to generate assembly for a file
src/playground/menu.cpp.s:
	$(MAKE) -f CMakeFiles/playground.dir/build.make CMakeFiles/playground.dir/src/playground/menu.cpp.s
.PHONY : src/playground/menu.cpp.s

src/playground/menuWindow.o: src/playground/menuWindow.cpp.o

.PHONY : src/playground/menuWindow.o

# target to build an object file
src/playground/menuWindow.cpp.o:
	$(MAKE) -f CMakeFiles/playground.dir/build.make CMakeFiles/playground.dir/src/playground/menuWindow.cpp.o
.PHONY : src/playground/menuWindow.cpp.o

src/playground/menuWindow.i: src/playground/menuWindow.cpp.i

.PHONY : src/playground/menuWindow.i

# target to preprocess a source file
src/playground/menuWindow.cpp.i:
	$(MAKE) -f CMakeFiles/playground.dir/build.make CMakeFiles/playground.dir/src/playground/menuWindow.cpp.i
.PHONY : src/playground/menuWindow.cpp.i

src/playground/menuWindow.s: src/playground/menuWindow.cpp.s

.PHONY : src/playground/menuWindow.s

# target to generate assembly for a file
src/playground/menuWindow.cpp.s:
	$(MAKE) -f CMakeFiles/playground.dir/build.make CMakeFiles/playground.dir/src/playground/menuWindow.cpp.s
.PHONY : src/playground/menuWindow.cpp.s

src/playground/mwindow.o: src/playground/mwindow.cpp.o

.PHONY : src/playground/mwindow.o

# target to build an object file
src/playground/mwindow.cpp.o:
	$(MAKE) -f CMakeFiles/playground.dir/build.make CMakeFiles/playground.dir/src/playground/mwindow.cpp.o
.PHONY : src/playground/mwindow.cpp.o

src/playground/mwindow.i: src/playground/mwindow.cpp.i

.PHONY : src/playground/mwindow.i

# target to preprocess a source file
src/playground/mwindow.cpp.i:
	$(MAKE) -f CMakeFiles/playground.dir/build.make CMakeFiles/playground.dir/src/playground/mwindow.cpp.i
.PHONY : src/playground/mwindow.cpp.i

src/playground/mwindow.s: src/playground/mwindow.cpp.s

.PHONY : src/playground/mwindow.s

# target to generate assembly for a file
src/playground/mwindow.cpp.s:
	$(MAKE) -f CMakeFiles/playground.dir/build.make CMakeFiles/playground.dir/src/playground/mwindow.cpp.s
.PHONY : src/playground/mwindow.cpp.s

src/playground/object.o: src/playground/object.cpp.o

.PHONY : src/playground/object.o

# target to build an object file
src/playground/object.cpp.o:
	$(MAKE) -f CMakeFiles/playground.dir/build.make CMakeFiles/playground.dir/src/playground/object.cpp.o
.PHONY : src/playground/object.cpp.o

src/playground/object.i: src/playground/object.cpp.i

.PHONY : src/playground/object.i

# target to preprocess a source file
src/playground/object.cpp.i:
	$(MAKE) -f CMakeFiles/playground.dir/build.make CMakeFiles/playground.dir/src/playground/object.cpp.i
.PHONY : src/playground/object.cpp.i

src/playground/object.s: src/playground/object.cpp.s

.PHONY : src/playground/object.s

# target to generate assembly for a file
src/playground/object.cpp.s:
	$(MAKE) -f CMakeFiles/playground.dir/build.make CMakeFiles/playground.dir/src/playground/object.cpp.s
.PHONY : src/playground/object.cpp.s

src/playground/player.o: src/playground/player.cpp.o

.PHONY : src/playground/player.o

# target to build an object file
src/playground/player.cpp.o:
	$(MAKE) -f CMakeFiles/playground.dir/build.make CMakeFiles/playground.dir/src/playground/player.cpp.o
.PHONY : src/playground/player.cpp.o

src/playground/player.i: src/playground/player.cpp.i

.PHONY : src/playground/player.i

# target to preprocess a source file
src/playground/player.cpp.i:
	$(MAKE) -f CMakeFiles/playground.dir/build.make CMakeFiles/playground.dir/src/playground/player.cpp.i
.PHONY : src/playground/player.cpp.i

src/playground/player.s: src/playground/player.cpp.s

.PHONY : src/playground/player.s

# target to generate assembly for a file
src/playground/player.cpp.s:
	$(MAKE) -f CMakeFiles/playground.dir/build.make CMakeFiles/playground.dir/src/playground/player.cpp.s
.PHONY : src/playground/player.cpp.s

src/playground/quad.o: src/playground/quad.cpp.o

.PHONY : src/playground/quad.o

# target to build an object file
src/playground/quad.cpp.o:
	$(MAKE) -f CMakeFiles/playground.dir/build.make CMakeFiles/playground.dir/src/playground/quad.cpp.o
.PHONY : src/playground/quad.cpp.o

src/playground/quad.i: src/playground/quad.cpp.i

.PHONY : src/playground/quad.i

# target to preprocess a source file
src/playground/quad.cpp.i:
	$(MAKE) -f CMakeFiles/playground.dir/build.make CMakeFiles/playground.dir/src/playground/quad.cpp.i
.PHONY : src/playground/quad.cpp.i

src/playground/quad.s: src/playground/quad.cpp.s

.PHONY : src/playground/quad.s

# target to generate assembly for a file
src/playground/quad.cpp.s:
	$(MAKE) -f CMakeFiles/playground.dir/build.make CMakeFiles/playground.dir/src/playground/quad.cpp.s
.PHONY : src/playground/quad.cpp.s

src/playground/scene.o: src/playground/scene.cpp.o

.PHONY : src/playground/scene.o

# target to build an object file
src/playground/scene.cpp.o:
	$(MAKE) -f CMakeFiles/playground.dir/build.make CMakeFiles/playground.dir/src/playground/scene.cpp.o
.PHONY : src/playground/scene.cpp.o

src/playground/scene.i: src/playground/scene.cpp.i

.PHONY : src/playground/scene.i

# target to preprocess a source file
src/playground/scene.cpp.i:
	$(MAKE) -f CMakeFiles/playground.dir/build.make CMakeFiles/playground.dir/src/playground/scene.cpp.i
.PHONY : src/playground/scene.cpp.i

src/playground/scene.s: src/playground/scene.cpp.s

.PHONY : src/playground/scene.s

# target to generate assembly for a file
src/playground/scene.cpp.s:
	$(MAKE) -f CMakeFiles/playground.dir/build.make CMakeFiles/playground.dir/src/playground/scene.cpp.s
.PHONY : src/playground/scene.cpp.s

src/playground/sphere.o: src/playground/sphere.cpp.o

.PHONY : src/playground/sphere.o

# target to build an object file
src/playground/sphere.cpp.o:
	$(MAKE) -f CMakeFiles/playground.dir/build.make CMakeFiles/playground.dir/src/playground/sphere.cpp.o
.PHONY : src/playground/sphere.cpp.o

src/playground/sphere.i: src/playground/sphere.cpp.i

.PHONY : src/playground/sphere.i

# target to preprocess a source file
src/playground/sphere.cpp.i:
	$(MAKE) -f CMakeFiles/playground.dir/build.make CMakeFiles/playground.dir/src/playground/sphere.cpp.i
.PHONY : src/playground/sphere.cpp.i

src/playground/sphere.s: src/playground/sphere.cpp.s

.PHONY : src/playground/sphere.s

# target to generate assembly for a file
src/playground/sphere.cpp.s:
	$(MAKE) -f CMakeFiles/playground.dir/build.make CMakeFiles/playground.dir/src/playground/sphere.cpp.s
.PHONY : src/playground/sphere.cpp.s

src/playground/star.o: src/playground/star.cpp.o

.PHONY : src/playground/star.o

# target to build an object file
src/playground/star.cpp.o:
	$(MAKE) -f CMakeFiles/playground.dir/build.make CMakeFiles/playground.dir/src/playground/star.cpp.o
.PHONY : src/playground/star.cpp.o

src/playground/star.i: src/playground/star.cpp.i

.PHONY : src/playground/star.i

# target to preprocess a source file
src/playground/star.cpp.i:
	$(MAKE) -f CMakeFiles/playground.dir/build.make CMakeFiles/playground.dir/src/playground/star.cpp.i
.PHONY : src/playground/star.cpp.i

src/playground/star.s: src/playground/star.cpp.s

.PHONY : src/playground/star.s

# target to generate assembly for a file
src/playground/star.cpp.s:
	$(MAKE) -f CMakeFiles/playground.dir/build.make CMakeFiles/playground.dir/src/playground/star.cpp.s
.PHONY : src/playground/star.cpp.s

src/testing/camera.o: src/testing/camera.cpp.o

.PHONY : src/testing/camera.o

# target to build an object file
src/testing/camera.cpp.o:
	$(MAKE) -f CMakeFiles/testing.dir/build.make CMakeFiles/testing.dir/src/testing/camera.cpp.o
.PHONY : src/testing/camera.cpp.o

src/testing/camera.i: src/testing/camera.cpp.i

.PHONY : src/testing/camera.i

# target to preprocess a source file
src/testing/camera.cpp.i:
	$(MAKE) -f CMakeFiles/testing.dir/build.make CMakeFiles/testing.dir/src/testing/camera.cpp.i
.PHONY : src/testing/camera.cpp.i

src/testing/camera.s: src/testing/camera.cpp.s

.PHONY : src/testing/camera.s

# target to generate assembly for a file
src/testing/camera.cpp.s:
	$(MAKE) -f CMakeFiles/testing.dir/build.make CMakeFiles/testing.dir/src/testing/camera.cpp.s
.PHONY : src/testing/camera.cpp.s

src/testing/cube.o: src/testing/cube.cpp.o

.PHONY : src/testing/cube.o

# target to build an object file
src/testing/cube.cpp.o:
	$(MAKE) -f CMakeFiles/testing.dir/build.make CMakeFiles/testing.dir/src/testing/cube.cpp.o
.PHONY : src/testing/cube.cpp.o

src/testing/cube.i: src/testing/cube.cpp.i

.PHONY : src/testing/cube.i

# target to preprocess a source file
src/testing/cube.cpp.i:
	$(MAKE) -f CMakeFiles/testing.dir/build.make CMakeFiles/testing.dir/src/testing/cube.cpp.i
.PHONY : src/testing/cube.cpp.i

src/testing/cube.s: src/testing/cube.cpp.s

.PHONY : src/testing/cube.s

# target to generate assembly for a file
src/testing/cube.cpp.s:
	$(MAKE) -f CMakeFiles/testing.dir/build.make CMakeFiles/testing.dir/src/testing/cube.cpp.s
.PHONY : src/testing/cube.cpp.s

src/testing/main.o: src/testing/main.cpp.o

.PHONY : src/testing/main.o

# target to build an object file
src/testing/main.cpp.o:
	$(MAKE) -f CMakeFiles/testing.dir/build.make CMakeFiles/testing.dir/src/testing/main.cpp.o
.PHONY : src/testing/main.cpp.o

src/testing/main.i: src/testing/main.cpp.i

.PHONY : src/testing/main.i

# target to preprocess a source file
src/testing/main.cpp.i:
	$(MAKE) -f CMakeFiles/testing.dir/build.make CMakeFiles/testing.dir/src/testing/main.cpp.i
.PHONY : src/testing/main.cpp.i

src/testing/main.s: src/testing/main.cpp.s

.PHONY : src/testing/main.s

# target to generate assembly for a file
src/testing/main.cpp.s:
	$(MAKE) -f CMakeFiles/testing.dir/build.make CMakeFiles/testing.dir/src/testing/main.cpp.s
.PHONY : src/testing/main.cpp.s

src/testing/mwindow.o: src/testing/mwindow.cpp.o

.PHONY : src/testing/mwindow.o

# target to build an object file
src/testing/mwindow.cpp.o:
	$(MAKE) -f CMakeFiles/testing.dir/build.make CMakeFiles/testing.dir/src/testing/mwindow.cpp.o
.PHONY : src/testing/mwindow.cpp.o

src/testing/mwindow.i: src/testing/mwindow.cpp.i

.PHONY : src/testing/mwindow.i

# target to preprocess a source file
src/testing/mwindow.cpp.i:
	$(MAKE) -f CMakeFiles/testing.dir/build.make CMakeFiles/testing.dir/src/testing/mwindow.cpp.i
.PHONY : src/testing/mwindow.cpp.i

src/testing/mwindow.s: src/testing/mwindow.cpp.s

.PHONY : src/testing/mwindow.s

# target to generate assembly for a file
src/testing/mwindow.cpp.s:
	$(MAKE) -f CMakeFiles/testing.dir/build.make CMakeFiles/testing.dir/src/testing/mwindow.cpp.s
.PHONY : src/testing/mwindow.cpp.s

src/testing/object.o: src/testing/object.cpp.o

.PHONY : src/testing/object.o

# target to build an object file
src/testing/object.cpp.o:
	$(MAKE) -f CMakeFiles/testing.dir/build.make CMakeFiles/testing.dir/src/testing/object.cpp.o
.PHONY : src/testing/object.cpp.o

src/testing/object.i: src/testing/object.cpp.i

.PHONY : src/testing/object.i

# target to preprocess a source file
src/testing/object.cpp.i:
	$(MAKE) -f CMakeFiles/testing.dir/build.make CMakeFiles/testing.dir/src/testing/object.cpp.i
.PHONY : src/testing/object.cpp.i

src/testing/object.s: src/testing/object.cpp.s

.PHONY : src/testing/object.s

# target to generate assembly for a file
src/testing/object.cpp.s:
	$(MAKE) -f CMakeFiles/testing.dir/build.make CMakeFiles/testing.dir/src/testing/object.cpp.s
.PHONY : src/testing/object.cpp.s

src/testing/scene.o: src/testing/scene.cpp.o

.PHONY : src/testing/scene.o

# target to build an object file
src/testing/scene.cpp.o:
	$(MAKE) -f CMakeFiles/testing.dir/build.make CMakeFiles/testing.dir/src/testing/scene.cpp.o
.PHONY : src/testing/scene.cpp.o

src/testing/scene.i: src/testing/scene.cpp.i

.PHONY : src/testing/scene.i

# target to preprocess a source file
src/testing/scene.cpp.i:
	$(MAKE) -f CMakeFiles/testing.dir/build.make CMakeFiles/testing.dir/src/testing/scene.cpp.i
.PHONY : src/testing/scene.cpp.i

src/testing/scene.s: src/testing/scene.cpp.s

.PHONY : src/testing/scene.s

# target to generate assembly for a file
src/testing/scene.cpp.s:
	$(MAKE) -f CMakeFiles/testing.dir/build.make CMakeFiles/testing.dir/src/testing/scene.cpp.s
.PHONY : src/testing/scene.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... install/strip"
	@echo "... install"
	@echo "... list_install_components"
	@echo "... testing"
	@echo "... install/local"
	@echo "... playground"
	@echo "... edit_cache"
	@echo "... ppgso"
	@echo "... shaders"
	@echo "... rebuild_cache"
	@echo "... ppgso/image.o"
	@echo "... ppgso/image.i"
	@echo "... ppgso/image.s"
	@echo "... ppgso/image_bmp.o"
	@echo "... ppgso/image_bmp.i"
	@echo "... ppgso/image_bmp.s"
	@echo "... ppgso/image_raw.o"
	@echo "... ppgso/image_raw.i"
	@echo "... ppgso/image_raw.s"
	@echo "... ppgso/mesh.o"
	@echo "... ppgso/mesh.i"
	@echo "... ppgso/mesh.s"
	@echo "... ppgso/shader.o"
	@echo "... ppgso/shader.i"
	@echo "... ppgso/shader.s"
	@echo "... ppgso/texture.o"
	@echo "... ppgso/texture.i"
	@echo "... ppgso/texture.s"
	@echo "... ppgso/tiny_obj_loader.o"
	@echo "... ppgso/tiny_obj_loader.i"
	@echo "... ppgso/tiny_obj_loader.s"
	@echo "... ppgso/window.o"
	@echo "... ppgso/window.i"
	@echo "... ppgso/window.s"
	@echo "... shaders/color_frag_glsl.o"
	@echo "... shaders/color_frag_glsl.i"
	@echo "... shaders/color_frag_glsl.s"
	@echo "... shaders/color_vert_glsl.o"
	@echo "... shaders/color_vert_glsl.i"
	@echo "... shaders/color_vert_glsl.s"
	@echo "... shaders/convolution_frag_glsl.o"
	@echo "... shaders/convolution_frag_glsl.i"
	@echo "... shaders/convolution_frag_glsl.s"
	@echo "... shaders/convolution_vert_glsl.o"
	@echo "... shaders/convolution_vert_glsl.i"
	@echo "... shaders/convolution_vert_glsl.s"
	@echo "... shaders/diffuse_frag_glsl.o"
	@echo "... shaders/diffuse_frag_glsl.i"
	@echo "... shaders/diffuse_frag_glsl.s"
	@echo "... shaders/diffuse_vert_glsl.o"
	@echo "... shaders/diffuse_vert_glsl.i"
	@echo "... shaders/diffuse_vert_glsl.s"
	@echo "... shaders/texture_frag_glsl.o"
	@echo "... shaders/texture_frag_glsl.i"
	@echo "... shaders/texture_frag_glsl.s"
	@echo "... shaders/texture_vert_glsl.o"
	@echo "... shaders/texture_vert_glsl.i"
	@echo "... shaders/texture_vert_glsl.s"
	@echo "... src/playground/camera.o"
	@echo "... src/playground/camera.i"
	@echo "... src/playground/camera.s"
	@echo "... src/playground/cube.o"
	@echo "... src/playground/cube.i"
	@echo "... src/playground/cube.s"
	@echo "... src/playground/explosion.o"
	@echo "... src/playground/explosion.i"
	@echo "... src/playground/explosion.s"
	@echo "... src/playground/lamppost.o"
	@echo "... src/playground/lamppost.i"
	@echo "... src/playground/lamppost.s"
	@echo "... src/playground/main.o"
	@echo "... src/playground/main.i"
	@echo "... src/playground/main.s"
	@echo "... src/playground/menu.o"
	@echo "... src/playground/menu.i"
	@echo "... src/playground/menu.s"
	@echo "... src/playground/menuWindow.o"
	@echo "... src/playground/menuWindow.i"
	@echo "... src/playground/menuWindow.s"
	@echo "... src/playground/mwindow.o"
	@echo "... src/playground/mwindow.i"
	@echo "... src/playground/mwindow.s"
	@echo "... src/playground/object.o"
	@echo "... src/playground/object.i"
	@echo "... src/playground/object.s"
	@echo "... src/playground/player.o"
	@echo "... src/playground/player.i"
	@echo "... src/playground/player.s"
	@echo "... src/playground/quad.o"
	@echo "... src/playground/quad.i"
	@echo "... src/playground/quad.s"
	@echo "... src/playground/scene.o"
	@echo "... src/playground/scene.i"
	@echo "... src/playground/scene.s"
	@echo "... src/playground/sphere.o"
	@echo "... src/playground/sphere.i"
	@echo "... src/playground/sphere.s"
	@echo "... src/playground/star.o"
	@echo "... src/playground/star.i"
	@echo "... src/playground/star.s"
	@echo "... src/testing/camera.o"
	@echo "... src/testing/camera.i"
	@echo "... src/testing/camera.s"
	@echo "... src/testing/cube.o"
	@echo "... src/testing/cube.i"
	@echo "... src/testing/cube.s"
	@echo "... src/testing/main.o"
	@echo "... src/testing/main.i"
	@echo "... src/testing/main.s"
	@echo "... src/testing/mwindow.o"
	@echo "... src/testing/mwindow.i"
	@echo "... src/testing/mwindow.s"
	@echo "... src/testing/object.o"
	@echo "... src/testing/object.i"
	@echo "... src/testing/object.s"
	@echo "... src/testing/scene.o"
	@echo "... src/testing/scene.i"
	@echo "... src/testing/scene.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

